server.port=8088
spring.application.name=ms-reportes

ms.clientes.url=http://localhost:8081
ms.equipos.url=http://localhost:8082
ms.resenas.url=http://localhost:8083
ms.facturacion.url=http://localhost:8084

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
