server.port=${PORT:8088}
ms.clientes.url=${MS_CLIENTES_URL:http://localhost:8081}
ms.equipos.url=${MS_EQUIPOS_URL:http://localhost:8082}
ms.resenas.url=${MS_RESENAS_URL:http://localhost:8083}
ms.facturacion.url=${MS_FACTURACION_URL:http://localhost:8084}
