spring.application.name=api-gateway
server.port=8080

# ms-clientes (8081)
spring.cloud.gateway.routes[0].id=ms-clientes
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/clientes/**

# ms-equipos (8082)
spring.cloud.gateway.routes[1].id=ms-equipos
spring.cloud.gateway.routes[1].uri=${MICROSERVICE_EQUIPOS_URL}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/equipos/**

# ms-resenas (8083)
spring.cloud.gateway.routes[2].id=ms-resenas
spring.cloud.gateway.routes[2].uri=${MICROSERVICE_RESENAS_URL}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/resenas/**

# ms-facturacion (8084)
spring.cloud.gateway.routes[3].id=ms-facturacion
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/facturas/**

# ms-sucursales (8085)
spring.cloud.gateway.routes[4].id=ms-sucursales
spring.cloud.gateway.routes[4].uri=http://localhost:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/sucursales/**

# ms-notificaciones (8086)
spring.cloud.gateway.routes[5].id=ms-notificaciones
spring.cloud.gateway.routes[5].uri=http://localhost:8086
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/notificaciones/**

# ms-usuarios (8087)
spring.cloud.gateway.routes[6].id=ms-usuarios
spring.cloud.gateway.routes[6].uri=http://localhost:8087
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/usuarios/**

# ms-reportes (8088)
spring.cloud.gateway.routes[7].id=ms-reportes
spring.cloud.gateway.routes[7].uri=http://localhost:8088
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/reportes/**

# ms-auth (8089)
spring.cloud.gateway.routes[8].id=ms-auth
spring.cloud.gateway.routes[8].uri=http://localhost:8089
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/v1/auth/**

# Swagger de cada microservicio (ejemplo ms-clientes)
spring.cloud.gateway.routes[9].id=swagger-clientes
spring.cloud.gateway.routes[9].uri=http://localhost:8081
spring.cloud.gateway.routes[9].predicates[0]=Path=/swagger-ui/**, /api-docs/**, /v3/api-docs/**

logging.level.org.springframework.cloud.gateway=INFO