server.port=${PORT:8080}

# ms-auth
spring.cloud.gateway.routes[0].id=ms-auth
spring.cloud.gateway.routes[0].uri=${MS_AUTH_URL:https://ms-auth-production-e8df.up.railway.app}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

# ms-equipos
spring.cloud.gateway.routes[1].id=ms-equipos
spring.cloud.gateway.routes[1].uri=${MS_EQUIPOS_URL:https://ms-equipos-production.up.railway.app}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/equipos/**

# ms-resenas
spring.cloud.gateway.routes[2].id=ms-resenas
spring.cloud.gateway.routes[2].uri=${MS_RESENAS_URL:https://ms-resenas-production.up.railway.app}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/resenas/**

# Swagger
spring.cloud.gateway.routes[3].id=swagger-ui
spring.cloud.gateway.routes[3].uri=${MS_EQUIPOS_URL:https://ms-equipos-production.up.railway.app}
spring.cloud.gateway.routes[3].predicates[0]=Path=/swagger-ui/**, /v3/api-docs/**

logging.level.org.springframework.cloud.gateway=INFO
