server.port=${PORT:8080}

# ms-auth
spring.cloud.gateway.routes[0].id=ms-auth
spring.cloud.gateway.routes[0].uri=https://ms-auth-production-e8df.up.railway.app
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

# ms-equipos
spring.cloud.gateway.routes[1].id=ms-equipos
spring.cloud.gateway.routes[1].uri=https://ms-equipos-production.up.railway.app
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/equipos/**

# ms-resenas
spring.cloud.gateway.routes[2].id=ms-resenas
spring.cloud.gateway.routes[2].uri=https://ms-resenas-production.up.railway.app
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/resenas/**

logging.level.org.springframework.cloud.gateway=INFO