spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:sucursalesdb}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8085}
