server.port=8084
spring.application.name=ms-facturacion

spring.datasource.url=jdbc:h2:mem:facturaciondb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true

facturacion.iva=0.19

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
