server.port=8086
spring.application.name=ms-notificaciones

notificaciones.from=gimnasio@tudominio.cl
notificaciones.modo=simulacion

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
